### ISSUE TITLE
default public key: not set

### ISSUE THREAD

**Issue by livingstrong** [ilansmith/rsa#1]
Hi, 

I tried to set public key, but it always returns "default public key: not set".
Did i do something wrong?

jerry@ubuntu:~/github/rsa/test$ ./rsa_enc -x ./rsaKey.pub
default public key: not set

**Comment by ilansmith** [comment]
Hi,

I'm REEEEEALLY sorry I haven't replied. For some reason I was not notified of your message and I haven't visited my github for a while...

When using a short option notation that gets an argument, the argument needs to be adjacent to the option. That is:

BAD:
./rsa_enc -x ./rsaKey.pub

GOOD
./rsa_enc -x./rsaKey.pub           # no space between -x and rsaKey.pub

Note that you can set the RSA_KEYPATH environment variable to store your keys in a location of your choise.

**Comment by livingstrong** [comment]
thanks for your reply~~~~
My colleague had completed this part by other code base, thank you very very mush!! 

On Jan 4, 2015, at 16:58, Ilan Smith notifications@github.com wrote:

Hi,

I'm REEEEEALLY sorry I haven't replied. For some reason I was not notified of your message and I haven't visited my github for a while...

When using a short option notation that gets an argument, the argument needs to be adjacent to the option. That is:

BAD:
./rsa_enc -x ./rsaKey.pub

GOOD
./rsa_enc -x./rsaKey.pub # no space between -x and rsaKey.pub

Note that you can set the RSA_KEYPATH environment variable to store your keys in a location of your choise.
